version: '3'

tasks:
  build:
    cmds:
      - task: lint
      - go build .

  lint:
    cmds:
      - golangci-lint run ./...

  # run: VERSION=2.0.0 task build:release
  'build:release':
    cmds:
      - task: lint
      - python3 ./scripts/build-release
      
